name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test --if-present

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: success()  # This ensures the publish job only runs if the build job was successful

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js for publishing
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'  # Or the specific version you need for publishing
    - run: npm install
    - run: npm publish
      # Ensure you have this secret set up in your repo's settings

